<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.Data.SqlClient" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Npgsql" />
    <PackageReference Include="Respawn" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\DevStart.Application\DevStart.Application.csproj" />
    <ProjectReference Include="..\..\src\DevStart.Domain\DevStart.Domain.csproj" />
    <ProjectReference Include="..\..\src\DevStart.Infrastructure\DevStart.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\DevStart.SharedKernel\DevStart.SharedKernel.csproj" />
    <ProjectReference Include="..\..\src\DevStart.WebApi\DevStart.WebApi.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
