// <auto-generated />
using System;
using DevStart.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DevStart.Infrastructure.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DevStart.Domain.Admin.AdminActionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ActionType")
                        .HasColumnType("integer")
                        .HasColumnName("action_type");

                    b.Property<Guid?>("AdminUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("admin_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<int>("TargetType")
                        .HasColumnType("integer")
                        .HasColumnName("target_type");

                    b.HasKey("Id")
                        .HasName("pk_admin_action_logs");

                    b.HasIndex("AdminUserId")
                        .HasDatabaseName("ix_admin_action_logs_admin_user_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_admin_action_logs_created_at");

                    b.HasIndex("TargetType", "TargetId")
                        .HasDatabaseName("ix_admin_action_logs_target");

                    b.ToTable("admin_action_logs", "public");
                });

            modelBuilder.Entity("DevStart.Domain.ConsentDocuments.ConsentDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_active");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_consent_documents");

                    b.HasIndex("Type")
                        .IsUnique()
                        .HasDatabaseName("ix_consent_documents_type_active")
                        .HasFilter("is_active = true");

                    b.HasIndex("Type", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_consent_documents_type_version");

                    b.ToTable("consent_documents", "public");
                });

            modelBuilder.Entity("DevStart.Domain.DealDocuments.DealDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CapTableObjectKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cap_table_object_key");

                    b.Property<Guid>("DealId")
                        .HasColumnType("uuid")
                        .HasColumnName("deal_id");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at");

                    b.Property<string>("TermSheetObjectKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("term_sheet_object_key");

                    b.HasKey("Id")
                        .HasName("pk_deal_documents");

                    b.HasIndex("DealId")
                        .IsUnique()
                        .HasDatabaseName("ix_deal_documents_deal_id");

                    b.ToTable("deal_documents", "public");
                });

            modelBuilder.Entity("DevStart.Domain.EmailVerificationTokens.EmailVerificationToken", b =>
                {
                    b.Property<Guid>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("token_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("TokenId")
                        .HasName("pk_email_verification_tokens");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_email_verification_tokens_user_id");

                    b.ToTable("email_verification_tokens", "public");
                });

            modelBuilder.Entity("DevStart.Domain.ExpertCollaborationRequests.ExpertCollaborationRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CollaborationType")
                        .HasColumnType("integer")
                        .HasColumnName("collaboration_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ExpertProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("expert_profile_id");

                    b.Property<string>("Message")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("message");

                    b.Property<int?>("ProposedHoursPerWeek")
                        .HasColumnType("integer")
                        .HasColumnName("proposed_hours_per_week");

                    b.Property<decimal?>("ProposedRate")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("proposed_rate");

                    b.Property<Guid>("StartupId")
                        .HasColumnType("uuid")
                        .HasColumnName("startup_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_expert_collaboration_requests");

                    b.HasIndex("ExpertProfileId", "StartupId")
                        .IsUnique()
                        .HasDatabaseName("ux_expert_collaboration_requests_expert_startup_pending")
                        .HasFilter("status = 0");

                    b.HasIndex("ExpertProfileId", "Status")
                        .HasDatabaseName("ix_expert_collaboration_requests_expert_status");

                    b.HasIndex("StartupId", "Status")
                        .HasDatabaseName("ix_expert_collaboration_requests_startup_status");

                    b.ToTable("expert_collaboration_requests", "public");
                });

            modelBuilder.Entity("DevStart.Domain.Experts.ExpertExperience", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("company");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<Guid>("ExpertProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("expert_profile_id");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("position");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_expert_experiences");

                    b.HasIndex("ExpertProfileId")
                        .HasDatabaseName("ix_expert_experiences_expert_profile_id");

                    b.ToTable("expert_experiences", "public");
                });

            modelBuilder.Entity("DevStart.Domain.Experts.ExpertProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_expert_profiles");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_expert_profiles_user_id");

                    b.ToTable("expert_profiles", "public");
                });

            modelBuilder.Entity("DevStart.Domain.Experts.ExpertProfileSpecialization", b =>
                {
                    b.Property<Guid>("ExpertProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("expert_profile_id");

                    b.Property<int>("Specialization")
                        .HasColumnType("integer")
                        .HasColumnName("specialization");

                    b.HasKey("ExpertProfileId", "Specialization")
                        .HasName("pk_expert_profile_specializations");

                    b.HasIndex("Specialization")
                        .HasDatabaseName("ix_expert_profile_specializations_specialization");

                    b.ToTable("expert_profile_specializations", "public");
                });

            modelBuilder.Entity("DevStart.Domain.ExternalLogins.ExternalLogin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<DateTime>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<int>("Provider")
                        .HasColumnType("integer")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderUserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("provider_user_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_external_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_external_logins_user_id");

                    b.HasIndex("Provider", "ProviderUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_external_logins_provider_provider_user_id");

                    b.ToTable("external_logins", "public");
                });

            modelBuilder.Entity("DevStart.Domain.InvestmentApplications.InvestmentApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("Discount")
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("discount");

                    b.Property<int>("Instrument")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("instrument");

                    b.Property<decimal?>("InterestRate")
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("interest_rate");

                    b.Property<Guid>("InvestorProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("investor_profile_id");

                    b.Property<decimal>("LiquidationPreference")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(5,2)")
                        .HasDefaultValue(1.0m)
                        .HasColumnName("liquidation_preference");

                    b.Property<string>("Message")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("message");

                    b.Property<decimal?>("PreMoneyValuation")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("pre_money_valuation");

                    b.Property<bool>("ProRataRights")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("pro_rata_rights");

                    b.Property<Guid?>("RoadmapItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("roadmap_item_id");

                    b.Property<Guid>("StartupId")
                        .HasColumnType("uuid")
                        .HasColumnName("startup_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int?>("TermMonths")
                        .HasColumnType("integer")
                        .HasColumnName("term_months");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal?>("ValuationCap")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valuation_cap");

                    b.HasKey("Id")
                        .HasName("pk_investment_applications");

                    b.HasIndex("RoadmapItemId")
                        .HasDatabaseName("ix_investment_applications_roadmap_item_id");

                    b.HasIndex("InvestorProfileId", "Status")
                        .HasDatabaseName("ix_investment_applications_investor_status");

                    b.HasIndex("StartupId", "Status")
                        .HasDatabaseName("ix_investment_applications_startup_status");

                    b.ToTable("investment_applications", "public");
                });

            modelBuilder.Entity("DevStart.Domain.InvestmentDeals.InvestmentDeal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<bool>("ConfirmedByInvestor")
                        .HasColumnType("boolean")
                        .HasColumnName("confirmed_by_investor");

                    b.Property<bool>("ConfirmedByStartup")
                        .HasColumnType("boolean")
                        .HasColumnName("confirmed_by_startup");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("Discount")
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("discount");

                    b.Property<int>("Instrument")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("instrument");

                    b.Property<decimal?>("InterestRate")
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("interest_rate");

                    b.Property<Guid>("InvestorProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("investor_profile_id");

                    b.Property<decimal>("LiquidationPreference")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(5,2)")
                        .HasDefaultValue(1.0m)
                        .HasColumnName("liquidation_preference");

                    b.Property<decimal?>("PreMoneyValuation")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("pre_money_valuation");

                    b.Property<bool>("ProRataRights")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("pro_rata_rights");

                    b.Property<Guid?>("RoadmapItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("roadmap_item_id");

                    b.Property<Guid>("StartupId")
                        .HasColumnType("uuid")
                        .HasColumnName("startup_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int?>("TermMonths")
                        .HasColumnType("integer")
                        .HasColumnName("term_months");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal?>("ValuationCap")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valuation_cap");

                    b.HasKey("Id")
                        .HasName("pk_investment_deals");

                    b.HasIndex("ApplicationId")
                        .IsUnique()
                        .HasDatabaseName("ix_investment_deals_application_id");

                    b.HasIndex("InvestorProfileId", "Status")
                        .HasDatabaseName("ix_investment_deals_investor_status");

                    b.HasIndex("StartupId", "Status")
                        .HasDatabaseName("ix_investment_deals_startup_status");

                    b.ToTable("investment_deals", "public");
                });

            modelBuilder.Entity("DevStart.Domain.Investors.InvestorProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_investor_profiles");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_investor_profiles_type");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_investor_profiles_user_id");

                    b.ToTable("investor_profiles", "public");
                });

            modelBuilder.Entity("DevStart.Domain.InviteTokens.InviteToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_used");

                    b.Property<Guid>("StartupId")
                        .HasColumnType("uuid")
                        .HasColumnName("startup_id");

                    b.HasKey("Id")
                        .HasName("pk_invite_tokens");

                    b.HasIndex("StartupId")
                        .HasDatabaseName("ix_invite_tokens_startup_id");

                    b.HasIndex("IsUsed", "ExpiresAt")
                        .HasDatabaseName("ix_invite_tokens_is_used_expires_at");

                    b.ToTable("invite_tokens", "public");
                });

            modelBuilder.Entity("DevStart.Domain.MediaFiles.MediaFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Bucket")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bucket");

                    b.Property<int>("FileSize")
                        .HasColumnType("integer")
                        .HasColumnName("file_size");

                    b.Property<int>("FileType")
                        .HasColumnType("integer")
                        .HasColumnName("file_type");

                    b.Property<string>("ObjectName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("object_name");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("upload_date");

                    b.Property<Guid>("UploaderId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploader_id");

                    b.HasKey("Id")
                        .HasName("pk_media_files");

                    b.ToTable("media_files", "public");
                });

            modelBuilder.Entity("DevStart.Domain.Messages.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<string>("MediaIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("media_ids");

                    b.Property<string>("MetricIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metric_ids");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("uuid")
                        .HasColumnName("receiver_id");

                    b.Property<int>("ReceiverType")
                        .HasColumnType("integer")
                        .HasColumnName("receiver_type");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_id");

                    b.Property<int>("SenderType")
                        .HasColumnType("integer")
                        .HasColumnName("sender_type");

                    b.Property<string>("TextContent")
                        .HasColumnType("text")
                        .HasColumnName("text_content");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_messages");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_messages_created_at");

                    b.HasIndex("ReceiverId", "IsRead")
                        .HasDatabaseName("ix_messages_receiver_is_read");

                    b.HasIndex("SenderId", "ReceiverId")
                        .HasDatabaseName("ix_messages_sender_receiver");

                    b.ToTable("messages", "public");
                });

            modelBuilder.Entity("DevStart.Domain.Notifications.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("reference_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_notifications_created_at");

                    b.HasIndex("UserId", "IsRead")
                        .HasDatabaseName("ix_notifications_user_id_is_read");

                    b.ToTable("notifications", "public");
                });

            modelBuilder.Entity("DevStart.Domain.PasswordResetTokens.PasswordResetToken", b =>
                {
                    b.Property<Guid>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("token_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("TokenId")
                        .HasName("pk_password_reset_tokens");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_password_reset_tokens_user_id");

                    b.ToTable("password_reset_tokens", "public");
                });

            modelBuilder.Entity("DevStart.Domain.Payments.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("amount");

                    b.Property<string>("ConfirmationUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("confirmation_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<decimal>("DiscountAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(10,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("discount_amount");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<Guid?>("PromoCodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("promo_code_id");

                    b.Property<int>("Provider")
                        .HasColumnType("integer")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderPaymentId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("provider_payment_id");

                    b.Property<decimal>("RefundedAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(10,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("refunded_amount");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("subscription_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_payments");

                    b.HasIndex("PromoCodeId")
                        .HasDatabaseName("ix_payments_promo_code_id");

                    b.HasIndex("SubscriptionId")
                        .HasDatabaseName("ix_payments_subscription_id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_payments_user_pending")
                        .HasFilter("status = 0");

                    b.HasIndex("Provider", "ProviderPaymentId")
                        .IsUnique()
                        .HasDatabaseName("ix_payments_provider_payment")
                        .HasFilter("provider_payment_id IS NOT NULL");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_payments_status_created");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("ix_payments_user_status");

                    b.ToTable("payments", "public");
                });

            modelBuilder.Entity("DevStart.Domain.Profiles.Profile", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid?>("AvatarId")
                        .HasColumnType("uuid")
                        .HasColumnName("avatar_id");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<string>("GitHubUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("github_url");

                    b.Property<bool>("IsAvailableForHire")
                        .HasColumnType("boolean")
                        .HasColumnName("is_available_for_hire");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<string>("LinkedInUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("linkedin_url");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("SocialMediaLinks")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("social_media_links");

                    b.Property<string>("TelegramUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("telegram_url");

                    b.Property<string>("TwitterUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("twitter_url");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.Property<int>("ViewCount")
                        .HasColumnType("integer")
                        .HasColumnName("view_count");

                    b.HasKey("UserId")
                        .HasName("pk_profiles");

                    b.ToTable("profiles", "public");
                });

            modelBuilder.Entity("DevStart.Domain.PromoCodes.PromoCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<int>("DiscountType")
                        .HasColumnType("integer")
                        .HasColumnName("discount_type");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("discount_value");

                    b.Property<int?>("FreePeriodDays")
                        .HasColumnType("integer")
                        .HasColumnName("free_period_days");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int?>("MaxRedemptions")
                        .HasColumnType("integer")
                        .HasColumnName("max_redemptions");

                    b.Property<int>("Plan")
                        .HasColumnType("integer")
                        .HasColumnName("plan");

                    b.Property<int>("RedeemedCount")
                        .HasColumnType("integer")
                        .HasColumnName("redeemed_count");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTime?>("ValidUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_until");

                    b.HasKey("Id")
                        .HasName("pk_promo_codes");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_promo_codes_code");

                    b.ToTable("promo_codes", "public");
                });

            modelBuilder.Entity("DevStart.Domain.PromoCodes.PromoCodeRedemption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("DiscountApplied")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("discount_applied");

                    b.Property<Guid?>("PaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.Property<Guid>("PromoCodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("promo_code_id");

                    b.Property<DateTime>("RedeemedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("redeemed_at");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("subscription_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_promo_code_redemptions");

                    b.HasIndex("PromoCodeId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_promo_code_redemptions_promo_user");

                    b.ToTable("promo_code_redemptions", "public");
                });

            modelBuilder.Entity("DevStart.Domain.RefreshTokens.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("created_by_ip");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_token_id");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_refresh_tokens_expires_at");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", "public");
                });

            modelBuilder.Entity("DevStart.Domain.StartupCommunityStandards.StartupCommunityDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("StartupId")
                        .HasColumnType("uuid")
                        .HasColumnName("startup_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_startup_community_documents");

                    b.HasIndex("StartupId", "Type")
                        .IsUnique()
                        .HasDatabaseName("ix_startup_community_documents_startup_id_type");

                    b.ToTable("startup_community_documents", "public");
                });

            modelBuilder.Entity("DevStart.Domain.StartupCommunityStandards.StartupCommunityStandards", b =>
                {
                    b.Property<Guid>("StartupId")
                        .HasColumnType("uuid")
                        .HasColumnName("startup_id");

                    b.Property<int>("CompletedCount")
                        .HasColumnType("integer")
                        .HasColumnName("completed_count");

                    b.Property<DateTime>("ComputedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("computed_at");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<int>("TotalCount")
                        .HasColumnType("integer")
                        .HasColumnName("total_count");

                    b.HasKey("StartupId")
                        .HasName("pk_startup_community_standards");

                    b.HasIndex("Level")
                        .HasDatabaseName("ix_startup_community_standards_level");

                    b.ToTable("startup_community_standards", "public");
                });

            modelBuilder.Entity("DevStart.Domain.StartupCompetitors.StartupCompetitor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("StartupId")
                        .HasColumnType("uuid")
                        .HasColumnName("startup_id");

                    b.Property<string>("StrengthsVsUs")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("strengths_vs_us");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WeaknessesVsUs")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("weaknesses_vs_us");

                    b.Property<string>("Website")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("website");

                    b.HasKey("Id")
                        .HasName("pk_startup_competitors");

                    b.HasIndex("StartupId")
                        .HasDatabaseName("ix_startup_competitors_startup_id");

                    b.ToTable("startup_competitors", "public");
                });

            modelBuilder.Entity("DevStart.Domain.StartupDocumentFiles.StartupDocumentFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Bucket")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bucket");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("document_name");

                    b.Property<int>("DocumentType")
                        .HasColumnType("integer")
                        .HasColumnName("document_type");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<string>("ObjectName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("object_name");

                    b.Property<Guid>("StartupId")
                        .HasColumnType("uuid")
                        .HasColumnName("startup_id");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("upload_date");

                    b.Property<Guid>("UploaderId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploader_id");

                    b.HasKey("Id")
                        .HasName("pk_startup_document_files");

                    b.ToTable("startup_document_files", "public");
                });

            modelBuilder.Entity("DevStart.Domain.StartupEquity.StartupEquityHolder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("CliffMonths")
                        .HasColumnType("integer")
                        .HasColumnName("cliff_months");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("EquityPercentage")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("equity_percentage");

                    b.Property<int>("HolderType")
                        .HasColumnType("integer")
                        .HasColumnName("holder_type");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<Guid>("StartupId")
                        .HasColumnType("uuid")
                        .HasColumnName("startup_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("VestingMonths")
                        .HasColumnType("integer")
                        .HasColumnName("vesting_months");

                    b.Property<DateTime?>("VestingStartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("vesting_start_date");

                    b.HasKey("Id")
                        .HasName("pk_startup_equity_holders");

                    b.HasIndex("StartupId")
                        .HasDatabaseName("ix_startup_equity_holders_startup_id");

                    b.ToTable("startup_equity_holders", "public");
                });

            modelBuilder.Entity("DevStart.Domain.StartupFollowers.StartupFollower", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<Guid>("StartupId")
                        .HasColumnType("uuid")
                        .HasColumnName("startup_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("ProfileId", "StartupId")
                        .HasName("pk_startup_followers");

                    b.ToTable("startup_followers", "public");
                });

            modelBuilder.Entity("DevStart.Domain.StartupInvestors.StartupInvestor", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<Guid>("StartupId")
                        .HasColumnType("uuid")
                        .HasColumnName("startup_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ProfileId", "StartupId")
                        .HasName("pk_startup_investors");

                    b.ToTable("startup_investors", "public");
                });

            modelBuilder.Entity("DevStart.Domain.StartupMembers.StartupMember", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<Guid>("StartupId")
                        .HasColumnType("uuid")
                        .HasColumnName("startup_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool?>("HasPriorExit")
                        .HasColumnType("boolean")
                        .HasColumnName("has_prior_exit");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<int?>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<int?>("PreviousStartupsCount")
                        .HasColumnType("integer")
                        .HasColumnName("previous_startups_count");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("YearsOfExperience")
                        .HasColumnType("integer")
                        .HasColumnName("years_of_experience");

                    b.HasKey("ProfileId", "StartupId")
                        .HasName("pk_startup_members");

                    b.ToTable("startup_members", "public");
                });

            modelBuilder.Entity("DevStart.Domain.StartupMetrics.StartupMetric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("MetricType")
                        .HasColumnType("integer")
                        .HasColumnName("metric_type");

                    b.Property<Guid>("StartupId")
                        .HasColumnType("uuid")
                        .HasColumnName("startup_id");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_startup_metrics");

                    b.HasIndex("StartupId")
                        .HasDatabaseName("ix_startup_metrics_startup_id");

                    b.ToTable("startup_metrics", "public");
                });

            modelBuilder.Entity("DevStart.Domain.StartupProducts.StartupProduct", b =>
                {
                    b.Property<Guid>("StartupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("startup_id");

                    b.Property<string>("Differentiators")
                        .HasColumnType("text")
                        .HasColumnName("differentiators");

                    b.Property<string>("Problem")
                        .HasColumnType("text")
                        .HasColumnName("problem");

                    b.Property<string>("Solution")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("solution");

                    b.Property<string>("Stack")
                        .HasColumnType("jsonb")
                        .HasColumnName("stack");

                    b.Property<string>("ValueProposition")
                        .HasColumnType("text")
                        .HasColumnName("value_proposition");

                    b.HasKey("StartupId")
                        .HasName("pk_startup_products");

                    b.ToTable("startup_products", "public");
                });

            modelBuilder.Entity("DevStart.Domain.StartupRoadmapItems.StartupRoadmapItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Desription")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("StartupId")
                        .HasColumnType("uuid")
                        .HasColumnName("startup_id");

                    b.Property<int>("StartupStage")
                        .HasColumnType("integer")
                        .HasColumnName("startup_stage");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<decimal?>("TargetAmount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("target_amount");

                    b.Property<DateTime>("TargetDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("target_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_startup_roadmap_items");

                    b.HasIndex("StartupId")
                        .HasDatabaseName("ix_startup_roadmap_items_startup_id");

                    b.ToTable("startup_roadmap_items", "public");
                });

            modelBuilder.Entity("DevStart.Domain.Startups.Startup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AvatarId")
                        .HasColumnType("uuid")
                        .HasColumnName("avatar_id");

                    b.Property<DateTime?>("BanExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ban_expires_at");

                    b.Property<string>("BanReason")
                        .HasColumnType("text")
                        .HasColumnName("ban_reason");

                    b.Property<DateTime?>("BannedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("banned_at");

                    b.Property<Guid?>("BannedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("banned_by_user_id");

                    b.Property<string>("BillingEmail")
                        .HasColumnType("text")
                        .HasColumnName("billing_email");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("HasPatents")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("has_patents");

                    b.Property<bool>("HasStrategicPartnerships")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("has_strategic_partnerships");

                    b.Property<int>("Industry")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("industry");

                    b.Property<bool>("IsBanned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_banned");

                    b.Property<bool>("IsStopped")
                        .HasColumnType("boolean")
                        .HasColumnName("is_stopped");

                    b.Property<int?>("Location")
                        .HasColumnType("integer")
                        .HasColumnName("location");

                    b.Property<decimal?>("MarketGrowthRate")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("market_growth_rate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PublicEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("public_email");

                    b.Property<decimal?>("Sam")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("sam");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("text")
                        .HasColumnName("short_description");

                    b.Property<string>("SocialMediaLinks")
                        .HasColumnType("jsonb")
                        .HasColumnName("social_media_links");

                    b.Property<decimal?>("Som")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("som");

                    b.Property<int>("Stage")
                        .HasColumnType("integer")
                        .HasColumnName("stage");

                    b.Property<decimal?>("Tam")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("tam");

                    b.Property<decimal?>("TargetRoundAmount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("target_round_amount");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_startups");

                    b.HasIndex("IsBanned", "BanExpiresAt")
                        .HasDatabaseName("ix_startups_banned");

                    b.ToTable("startups", "public");
                });

            modelBuilder.Entity("DevStart.Domain.Startups.StartupValuationSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BreakdownJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("breakdown_json");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("calculated_at");

                    b.Property<decimal>("CompetitionScore")
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("competition_score");

                    b.Property<decimal>("MarketScore")
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("market_score");

                    b.Property<string>("MethodologyVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("methodology_version");

                    b.Property<string>("MethodsUsed")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("methods_used");

                    b.Property<decimal>("ProductScore")
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("product_score");

                    b.Property<Guid>("StartupId")
                        .HasColumnType("uuid")
                        .HasColumnName("startup_id");

                    b.Property<decimal>("TeamScore")
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("team_score");

                    b.Property<decimal>("TotalScore")
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("total_score");

                    b.Property<decimal>("TractionScore")
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("traction_score");

                    b.Property<decimal>("ValuationHigh")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valuation_high");

                    b.Property<decimal>("ValuationLow")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valuation_low");

                    b.Property<decimal>("ValuationPoint")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valuation_point");

                    b.HasKey("Id")
                        .HasName("pk_startup_valuation_snapshots");

                    b.HasIndex("StartupId", "CalculatedAt")
                        .HasDatabaseName("ix_startup_valuation_snapshots_startup_calculated");

                    b.ToTable("startup_valuation_snapshots", "public");
                });

            modelBuilder.Entity("DevStart.Domain.Subscriptions.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int>("Plan")
                        .HasColumnType("integer")
                        .HasColumnName("plan");

                    b.Property<DateTime?>("RenewalReminderSentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("renewal_reminder_sent_at");

                    b.Property<int>("Source")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("source");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_subscriptions");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_subscriptions_expires_at");

                    b.HasIndex("Status", "ExpiresAt")
                        .HasDatabaseName("ix_subscriptions_status_expires");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("ix_subscriptions_user_status");

                    b.ToTable("subscriptions", "public");
                });

            modelBuilder.Entity("DevStart.Domain.TwoFactor.TwoFactorRecoveryCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code_hash");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_two_factor_recovery_codes");

                    b.HasIndex("UserId", "CodeHash")
                        .IsUnique()
                        .HasDatabaseName("ix_two_factor_recovery_codes_user_id_code_hash");

                    b.ToTable("two_factor_recovery_codes", "public");
                });

            modelBuilder.Entity("DevStart.Domain.TwoFactor.UserTwoFactor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("EnabledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enabled_at");

                    b.Property<string>("EncryptedSecret")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("encrypted_secret");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_enabled");

                    b.Property<long?>("LastUsedTimestep")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("last_used_timestep");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_two_factor");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_two_factor_user_id");

                    b.ToTable("user_two_factor", "public");
                });

            modelBuilder.Entity("DevStart.Domain.UserConsents.UserConsent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<string>("DocumentVersion")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("document_version");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("consent_type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_consents");

                    b.HasIndex("UserId", "Type")
                        .HasDatabaseName("ix_user_consents_user_id_consent_type");

                    b.ToTable("user_consents", "public");
                });

            modelBuilder.Entity("DevStart.Domain.UserPreferences.UserPreference", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<bool>("ReceiveNotifications")
                        .HasColumnType("boolean")
                        .HasColumnName("receive_notifications");

                    b.Property<int>("Theme")
                        .HasColumnType("integer")
                        .HasColumnName("theme");

                    b.HasKey("UserId")
                        .HasName("pk_user_preferences");

                    b.ToTable("user_preferences", "public");
                });

            modelBuilder.Entity("DevStart.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("BanExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ban_expires_at");

                    b.Property<string>("BanReason")
                        .HasColumnType("text")
                        .HasColumnName("ban_reason");

                    b.Property<DateTime?>("BannedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("banned_at");

                    b.Property<Guid?>("BannedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("banned_by_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<bool>("IsBanned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_banned");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_verified");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<int>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.HasIndex("IsBanned", "BanExpiresAt")
                        .HasDatabaseName("ix_users_banned");

                    b.ToTable("users", "public");
                });

            modelBuilder.Entity("DevStart.Domain.Valuation.ValuationBenchmark", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_from");

                    b.Property<int>("Industry")
                        .HasColumnType("integer")
                        .HasColumnName("industry");

                    b.Property<int>("MetricType")
                        .HasColumnType("integer")
                        .HasColumnName("metric_type");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("source");

                    b.Property<int?>("Stage")
                        .HasColumnType("integer")
                        .HasColumnName("stage");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_valuation_benchmark");

                    b.HasIndex("MetricType", "Industry", "Stage", "EffectiveFrom")
                        .IsUnique()
                        .HasDatabaseName("ux_valuation_benchmark_metric_industry_stage_effective");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("MetricType", "Industry", "Stage", "EffectiveFrom"), false);

                    b.ToTable("valuation_benchmark", "public");
                });

            modelBuilder.Entity("DevStart.Domain.Experts.ExpertProfile", b =>
                {
                    b.HasOne("DevStart.Domain.Profiles.Profile", "Profile")
                        .WithOne()
                        .HasForeignKey("DevStart.Domain.Experts.ExpertProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_expert_profiles_profiles_user_id");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("DevStart.Domain.Investors.InvestorProfile", b =>
                {
                    b.HasOne("DevStart.Domain.Profiles.Profile", "Profile")
                        .WithOne()
                        .HasForeignKey("DevStart.Domain.Investors.InvestorProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_investor_profiles_profiles_user_id");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("DevStart.Domain.Payments.Payment", b =>
                {
                    b.HasOne("DevStart.Domain.PromoCodes.PromoCode", null)
                        .WithMany()
                        .HasForeignKey("PromoCodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_payments_promo_codes_promo_code_id");

                    b.HasOne("DevStart.Domain.Subscriptions.Subscription", null)
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_payments_subscriptions_subscription_id");
                });

            modelBuilder.Entity("DevStart.Domain.PromoCodes.PromoCodeRedemption", b =>
                {
                    b.HasOne("DevStart.Domain.PromoCodes.PromoCode", null)
                        .WithMany()
                        .HasForeignKey("PromoCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_promo_code_redemptions_promo_codes_promo_code_id");
                });

            modelBuilder.Entity("DevStart.Domain.StartupMembers.StartupMember", b =>
                {
                    b.HasOne("DevStart.Domain.Profiles.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_startup_members_profiles_profile_id");

                    b.Navigation("Profile");
                });
#pragma warning restore 612, 618
        }
    }
}
