// <auto-generated />
using System;
using DevStart.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DevStart.Infrastructure.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DevStart.Domain.DealDocuments.DealDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CapTableObjectKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cap_table_object_key");

                    b.Property<Guid>("DealId")
                        .HasColumnType("uuid")
                        .HasColumnName("deal_id");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at");

                    b.Property<string>("TermSheetObjectKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("term_sheet_object_key");

                    b.HasKey("Id")
                        .HasName("pk_deal_documents");

                    b.HasIndex("DealId")
                        .IsUnique()
                        .HasDatabaseName("ix_deal_documents_deal_id");

                    b.ToTable("deal_documents", "public");
                });

            modelBuilder.Entity("DevStart.Domain.EmailVerificationTokens.EmailVerificationToken", b =>
                {
                    b.Property<Guid>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("token_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("TokenId")
                        .HasName("pk_email_verification_tokens");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_email_verification_tokens_user_id");

                    b.ToTable("email_verification_tokens", "public");
                });

            modelBuilder.Entity("DevStart.Domain.InvestmentApplications.InvestmentApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("Discount")
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("discount");

                    b.Property<int>("Instrument")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("instrument");

                    b.Property<decimal?>("InterestRate")
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("interest_rate");

                    b.Property<Guid>("InvestorProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("investor_profile_id");

                    b.Property<decimal>("LiquidationPreference")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(5,2)")
                        .HasDefaultValue(1.0m)
                        .HasColumnName("liquidation_preference");

                    b.Property<string>("Message")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("message");

                    b.Property<decimal?>("PreMoneyValuation")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("pre_money_valuation");

                    b.Property<bool>("ProRataRights")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("pro_rata_rights");

                    b.Property<Guid?>("RoadmapItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("roadmap_item_id");

                    b.Property<Guid>("StartupId")
                        .HasColumnType("uuid")
                        .HasColumnName("startup_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int?>("TermMonths")
                        .HasColumnType("integer")
                        .HasColumnName("term_months");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal?>("ValuationCap")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valuation_cap");

                    b.HasKey("Id")
                        .HasName("pk_investment_applications");

                    b.HasIndex("RoadmapItemId")
                        .HasDatabaseName("ix_investment_applications_roadmap_item_id");

                    b.HasIndex("InvestorProfileId", "Status")
                        .HasDatabaseName("ix_investment_applications_investor_status");

                    b.HasIndex("StartupId", "Status")
                        .HasDatabaseName("ix_investment_applications_startup_status");

                    b.ToTable("investment_applications", "public");
                });

            modelBuilder.Entity("DevStart.Domain.InvestmentDeals.InvestmentDeal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<bool>("ConfirmedByInvestor")
                        .HasColumnType("boolean")
                        .HasColumnName("confirmed_by_investor");

                    b.Property<bool>("ConfirmedByStartup")
                        .HasColumnType("boolean")
                        .HasColumnName("confirmed_by_startup");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("Discount")
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("discount");

                    b.Property<int>("Instrument")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("instrument");

                    b.Property<decimal?>("InterestRate")
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("interest_rate");

                    b.Property<Guid>("InvestorProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("investor_profile_id");

                    b.Property<decimal>("LiquidationPreference")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(5,2)")
                        .HasDefaultValue(1.0m)
                        .HasColumnName("liquidation_preference");

                    b.Property<decimal?>("PreMoneyValuation")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("pre_money_valuation");

                    b.Property<bool>("ProRataRights")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("pro_rata_rights");

                    b.Property<Guid?>("RoadmapItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("roadmap_item_id");

                    b.Property<Guid>("StartupId")
                        .HasColumnType("uuid")
                        .HasColumnName("startup_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int?>("TermMonths")
                        .HasColumnType("integer")
                        .HasColumnName("term_months");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal?>("ValuationCap")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valuation_cap");

                    b.HasKey("Id")
                        .HasName("pk_investment_deals");

                    b.HasIndex("ApplicationId")
                        .IsUnique()
                        .HasDatabaseName("ix_investment_deals_application_id");

                    b.HasIndex("InvestorProfileId", "Status")
                        .HasDatabaseName("ix_investment_deals_investor_status");

                    b.HasIndex("StartupId", "Status")
                        .HasDatabaseName("ix_investment_deals_startup_status");

                    b.ToTable("investment_deals", "public");
                });

            modelBuilder.Entity("DevStart.Domain.Investors.InvestorProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Bio")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("bio");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Website")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("website");

                    b.HasKey("Id")
                        .HasName("pk_investor_profiles");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_investor_profiles_type");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_investor_profiles_user_id");

                    b.ToTable("investor_profiles", "public");
                });

            modelBuilder.Entity("DevStart.Domain.InviteTokens.InviteToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_used");

                    b.Property<Guid>("StartupId")
                        .HasColumnType("uuid")
                        .HasColumnName("startup_id");

                    b.HasKey("Id")
                        .HasName("pk_invite_tokens");

                    b.HasIndex("StartupId")
                        .HasDatabaseName("ix_invite_tokens_startup_id");

                    b.HasIndex("IsUsed", "ExpiresAt")
                        .HasDatabaseName("ix_invite_tokens_is_used_expires_at");

                    b.ToTable("invite_tokens", "public");
                });

            modelBuilder.Entity("DevStart.Domain.MediaFiles.MediaFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Bucket")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bucket");

                    b.Property<int>("FileSize")
                        .HasColumnType("integer")
                        .HasColumnName("file_size");

                    b.Property<int>("FileType")
                        .HasColumnType("integer")
                        .HasColumnName("file_type");

                    b.Property<string>("ObjectName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("object_name");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("upload_date");

                    b.Property<Guid>("UploaderId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploader_id");

                    b.HasKey("Id")
                        .HasName("pk_media_files");

                    b.ToTable("media_files", "public");
                });

            modelBuilder.Entity("DevStart.Domain.Messages.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<string>("MediaIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("media_ids");

                    b.Property<string>("MetricIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metric_ids");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("uuid")
                        .HasColumnName("receiver_id");

                    b.Property<int>("ReceiverType")
                        .HasColumnType("integer")
                        .HasColumnName("receiver_type");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_id");

                    b.Property<int>("SenderType")
                        .HasColumnType("integer")
                        .HasColumnName("sender_type");

                    b.Property<string>("TextContent")
                        .HasColumnType("text")
                        .HasColumnName("text_content");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_messages");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_messages_created_at");

                    b.HasIndex("ReceiverId", "IsRead")
                        .HasDatabaseName("ix_messages_receiver_is_read");

                    b.HasIndex("SenderId", "ReceiverId")
                        .HasDatabaseName("ix_messages_sender_receiver");

                    b.ToTable("messages", "public");
                });

            modelBuilder.Entity("DevStart.Domain.Notifications.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("reference_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_notifications_created_at");

                    b.HasIndex("UserId", "IsRead")
                        .HasDatabaseName("ix_notifications_user_id_is_read");

                    b.ToTable("notifications", "public");
                });

            modelBuilder.Entity("DevStart.Domain.Profiles.Profile", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid?>("AvatarId")
                        .HasColumnType("uuid")
                        .HasColumnName("avatar_id");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<bool>("IsAvailableForHire")
                        .HasColumnType("boolean")
                        .HasColumnName("is_available_for_hire");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("SocialMediaLinks")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("social_media_links");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("UserId")
                        .HasName("pk_profiles");

                    b.ToTable("profiles", "public");
                });

            modelBuilder.Entity("DevStart.Domain.StartupCompetitors.StartupCompetitor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("StartupId")
                        .HasColumnType("uuid")
                        .HasColumnName("startup_id");

                    b.Property<string>("StrengthsVsUs")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("strengths_vs_us");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WeaknessesVsUs")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("weaknesses_vs_us");

                    b.Property<string>("Website")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("website");

                    b.HasKey("Id")
                        .HasName("pk_startup_competitors");

                    b.HasIndex("StartupId")
                        .HasDatabaseName("ix_startup_competitors_startup_id");

                    b.ToTable("startup_competitors", "public");
                });

            modelBuilder.Entity("DevStart.Domain.StartupDocumentFiles.StartupDocumentFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Bucket")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bucket");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("document_name");

                    b.Property<int>("DocumentType")
                        .HasColumnType("integer")
                        .HasColumnName("document_type");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<string>("ObjectName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("object_name");

                    b.Property<Guid>("StartupId")
                        .HasColumnType("uuid")
                        .HasColumnName("startup_id");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("upload_date");

                    b.Property<Guid>("UploaderId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploader_id");

                    b.HasKey("Id")
                        .HasName("pk_startup_document_files");

                    b.ToTable("startup_document_files", "public");
                });

            modelBuilder.Entity("DevStart.Domain.StartupFollowers.StartupFollower", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<Guid>("StartupId")
                        .HasColumnType("uuid")
                        .HasColumnName("startup_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("ProfileId", "StartupId")
                        .HasName("pk_startup_followers");

                    b.ToTable("startup_followers", "public");
                });

            modelBuilder.Entity("DevStart.Domain.StartupInvestors.StartupInvestor", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<Guid>("StartupId")
                        .HasColumnType("uuid")
                        .HasColumnName("startup_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ProfileId", "StartupId")
                        .HasName("pk_startup_investors");

                    b.ToTable("startup_investors", "public");
                });

            modelBuilder.Entity("DevStart.Domain.StartupMembers.StartupMember", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<Guid>("StartupId")
                        .HasColumnType("uuid")
                        .HasColumnName("startup_id");

                    b.Property<string>("Bio")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("bio");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool?>("HasPriorExit")
                        .HasColumnType("boolean")
                        .HasColumnName("has_prior_exit");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<int?>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<int?>("PreviousStartupsCount")
                        .HasColumnType("integer")
                        .HasColumnName("previous_startups_count");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("YearsOfExperience")
                        .HasColumnType("integer")
                        .HasColumnName("years_of_experience");

                    b.HasKey("ProfileId", "StartupId")
                        .HasName("pk_startup_members");

                    b.ToTable("startup_members", "public");
                });

            modelBuilder.Entity("DevStart.Domain.StartupMetrics.StartupMetric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("MetricType")
                        .HasColumnType("integer")
                        .HasColumnName("metric_type");

                    b.Property<Guid>("StartupId")
                        .HasColumnType("uuid")
                        .HasColumnName("startup_id");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_startup_metrics");

                    b.HasIndex("StartupId")
                        .HasDatabaseName("ix_startup_metrics_startup_id");

                    b.ToTable("startup_metrics", "public");
                });

            modelBuilder.Entity("DevStart.Domain.StartupProducts.StartupProduct", b =>
                {
                    b.Property<Guid>("StartupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("startup_id");

                    b.Property<string>("Differentiators")
                        .HasColumnType("text")
                        .HasColumnName("differentiators");

                    b.Property<string>("Problem")
                        .HasColumnType("text")
                        .HasColumnName("problem");

                    b.Property<string>("Solution")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("solution");

                    b.Property<string>("Stack")
                        .HasColumnType("jsonb")
                        .HasColumnName("stack");

                    b.Property<string>("ValueProposition")
                        .HasColumnType("text")
                        .HasColumnName("value_proposition");

                    b.HasKey("StartupId")
                        .HasName("pk_startup_products");

                    b.ToTable("startup_products", "public");
                });

            modelBuilder.Entity("DevStart.Domain.StartupRoadmapItems.StartupRoadmapItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Desription")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("StartupId")
                        .HasColumnType("uuid")
                        .HasColumnName("startup_id");

                    b.Property<int>("StartupStage")
                        .HasColumnType("integer")
                        .HasColumnName("startup_stage");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<decimal?>("TargetAmount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("target_amount");

                    b.Property<DateTime>("TargetDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("target_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_startup_roadmap_items");

                    b.HasIndex("StartupId")
                        .HasDatabaseName("ix_startup_roadmap_items_startup_id");

                    b.ToTable("startup_roadmap_items", "public");
                });

            modelBuilder.Entity("DevStart.Domain.Startups.Startup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AvatarId")
                        .HasColumnType("uuid")
                        .HasColumnName("avatar_id");

                    b.Property<string>("BillingEmail")
                        .HasColumnType("text")
                        .HasColumnName("billing_email");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("HasPatents")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("has_patents");

                    b.Property<bool>("IsStopped")
                        .HasColumnType("boolean")
                        .HasColumnName("is_stopped");

                    b.Property<int?>("Location")
                        .HasColumnType("integer")
                        .HasColumnName("location");

                    b.Property<decimal?>("MarketGrowthRate")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("market_growth_rate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PublicEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("public_email");

                    b.Property<decimal?>("Sam")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("sam");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("text")
                        .HasColumnName("short_description");

                    b.Property<string>("SocialMediaLinks")
                        .HasColumnType("jsonb")
                        .HasColumnName("social_media_links");

                    b.Property<decimal?>("Som")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("som");

                    b.Property<int>("Stage")
                        .HasColumnType("integer")
                        .HasColumnName("stage");

                    b.Property<decimal?>("Tam")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("tam");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_startups");

                    b.ToTable("startups", "public");
                });

            modelBuilder.Entity("DevStart.Domain.UserPreferences.UserPreference", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<bool>("ReceiveNotifications")
                        .HasColumnType("boolean")
                        .HasColumnName("receive_notifications");

                    b.Property<int>("Theme")
                        .HasColumnType("integer")
                        .HasColumnName("theme");

                    b.HasKey("UserId")
                        .HasName("pk_user_preferences");

                    b.ToTable("user_preferences", "public");
                });

            modelBuilder.Entity("DevStart.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_verified");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<int>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", "public");
                });
#pragma warning restore 612, 618
        }
    }
}
